### ISSUE TITLE
Is it correct to judge electron as node?

### ISSUE THREAD

**Issue by NoDocCat** [iliakan/detect-node#11]
I use a lib for my web page. it use this package to judge the lib should use read file or use document.getElementById for load tpl.
Now, I want run my web page in electron, but it not work.
I debug this page, I saw the lib use read file to load tpl. Because in electron this package return true.

I want to know if this is correct?

**Comment by wjhir** [comment]
Electron mixes node with the browser. You can be in node, in a browser, or both at the same time.

In your case, if you expect to be in a browser context, you should check for a browser, rather than checking that you're not in node.

**Comment by NoDocCat** [comment]
Thanks for your answer.
