### ISSUE TITLE
reliability question

### ISSUE THREAD

**Issue by simongfxu** [iliakan/detect-node#3]
I am not quite sure about the reliability.
Because I do not think we should trust the `process` property just like if we wanna detect browser we should never trust window or document.
I wrote a [library](https://github.com/sdkjs/hasdom) to check whether a javascript env has dom, hope it will help you anyway.

**Comment by dsamarin** [comment]
What we are trusting about the `process` property isn't the fact that it exists or has certain properties, but whether the internal `[[Class]]` property of this object is set to `"process"`. ECMAScript has no method to change this property. However it can be retrieved with Object.prototype.toString.call(process ? process : 0), returning `[object process]` or `[object Number]`.

**Comment by devdoomari** [comment]
how about adding some browserstack / saucelabs badge for more credibility?
I'm sure this library won't mess up with IE>8 and others, but it's more 'comforting' to see those badges : )

**Comment by wjhir** [comment]
The `toString` check is no longer reliable due to [Symbol.toStringTag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag).
```JavaScript
var process = {}
process[Symbol.toStringTag] = 'process'
console.log(process.toString()) // [object process]
```

**Comment by m-onz** [comment]
I think the way you've made this library will work 99% of the time.

I think checking whether the process object is problematic in the rare case that someone defines a process property on the window object.

Why don't you check for the existence of properties that the node process object contains.. for example...

* title: 'Windows PowerShell',
 * pid: 6316,

```js
if (process.hasOwnProperty('title') &&
   process.hasOwnProperty('pid') && typeof process.pid === 'number'
```
