### ISSUE TITLE
Publish licensed version

### ISSUE THREAD

**Issue by honzajavorek** [iliakan/detect-node#9]
@iliakan would you mind publishing a version of this library which contains the LICENSE file? As of now, the npm package is missing the file, thus it's effectively unlicensed and copyrighted code nobody can legally use (no, the SPDX identifier in the `package.json` file isn't enough).

It would be best to publish it as a patch release so it virally fixes all dependants up the chain.

Thanks!

**Comment by iliakan** [comment]
MIT

**Comment by iliakan** [comment]
Please suggest a PR with the proper file.

**Comment by honzajavorek** [comment]
@iliakan The file is already in the repository, otherwise I'd suggest a PR 🙂 However, the project is not published to the registry with the file. The MIT license says specifically it needs to be attached everywhere:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

The only thing needed is to issue a patch version and to release it. Would you accept a PR where I bump the version? I can't do the `npm publish` part, obviously. That would be up to you.

**Comment by honzajavorek** [comment]
To illustrate the issue:

```
$ npm i detect-node
$ ls node_modules/detect-node
Readme.md	index.js	package.json
```

**Comment by iliakan** [comment]
I will accept and republish.
